#pragma once

#include "OnnxEngine.h"

#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudaarithm.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudawarping.hpp>

#include <memory>
#include <string>

// ============================================================================
//  LaMa  -  ONNX Runtime-based Image Inpainting Engine  (quality-first)
// ============================================================================
//
//  ONNX I/O spec (generated by export_onnx.py):
//    Input  "gen_input"  [1, 4, H, W]  float32
//      ch 0-2 : masked_image = image_rgb * (1 - mask),  [0, 1]
//      ch 3   : binary mask {0.0, 1.0},  1 = region to inpaint
//    Output "predicted"  [1, 3, H, W]  float32,  [0, 1],  RGB
//
//  ONNX Runtime replaces TensorRT because TRT 10.x does not support the ONNX
//  DFT operator used in LaMa's 18 FFC blocks.  ONNX Runtime with the CUDA
//  Execution Provider handles DFT natively and keeps inference on the GPU.
//
//  Fixed inference resolution: EXPORT_H x EXPORT_W (default 512x512).
//    Inputs of any size are resized before inference and resized back after.
//
//  Pre/post-processing: fully on GPU (cv::cuda::GpuMat)
//    - OnnxEngine GPU buffers are referenced as GpuMat views (D2D, zero-copy).
//
//  Dependencies: CUDA 13.1,  cuDNN 9.17,  ONNX Runtime 1.24+,  OpenCV 4.13 (with cuda modules)
// ============================================================================

class LaMa
{
public:
    // onnxModelPath : path to lama.onnx
    explicit LaMa(const std::string& onnxModelPath);
    ~LaMa() = default;

    bool isReady() const { return m_bReady; }

    // ── Main inference function ───────────────────────────────────────────────
    //
    // imageBGR : CV_8UC3  BGR source image (up to 2048x2048)
    // mask     : CV_8UC1 or CV_8UC3
    //            white (> 0) = region to inpaint,  black (0) = keep
    //            threshold matches original Python: pixel > 0 -> inpaint
    //
    // Returns  : CV_8UC3 BGR inpainted result (same resolution as imageBGR)
    //            Returns empty cv::Mat{} on error
    cv::Mat inpaint(const cv::Mat& imageBGR, const cv::Mat& mask);

private:
    // ── Preprocessing (fully on GPU) ─────────────────────────────────────────
    //  1. BGR->RGB,  [0,255]->[0,1] normalization
    //  2. mask binarization: > 0 -> 1.0  (matches original Python behavior)
    //  3. zero-padding to nearest multiple of 32
    //  4. masked_image = rgb * (1 - mask)
    //  5. NCHW [R,G,B,mask] -> TRT input buffer (D2D copy)
    //  6. update TRT context input shape for current resolution
    void preprocess(const cv::Mat& imageBGR, const cv::Mat& mask);

    // ── Postprocessing (fully on GPU) ────────────────────────────────────────
    //  1. TRT output buffer -> 3-channel GpuMat  (D2D view, no copy)
    //  2. sigmoid output clipping [0, 1]
    //  3. compositing: result = mask * predicted + (1 - mask) * original
    //  4. [0,1]->[0,255] conversion,  RGB->BGR
    //  5. download to CPU -> crop to origH x origW
    cv::Mat postprocess();

    inline void checkCudaErrorCode(cudaError_t code);

    // ── Member variables ──────────────────────────────────────────────────────

    std::unique_ptr<OnnxEngine> m_onnxEngine;
    bool m_bReady = false;

    // GPU I/O buffer pointers (owned by OnnxEngine, cached after load)
    void* m_inputBuffer  = nullptr;   // [1, 4, EXPORT_H, EXPORT_W] float32
    void* m_outputBuffer = nullptr;   // [1, 3, EXPORT_H, EXPORT_W] float32

    // Preprocessing results stored on GPU (reused in postprocessing compositing)
    cv::cuda::GpuMat m_gpuOrigPadRGB;  // float32 3ch RGB [0,1], includes padding
    cv::cuda::GpuMat m_gpuMaskPad;     // float32 1ch {0,1},     includes padding

    int32_t m_inferH = 0;   // padded height (multiple of 32)
    int32_t m_inferW = 0;   // padded width  (multiple of 32)
    int32_t m_origH  = 0;   // original image height
    int32_t m_origW  = 0;   // original image width

    // Fixed inference resolution matching the static ONNX export size.
    // Must match the --opt-size used in export_onnx.py (default: 512).
    static constexpr int32_t EXPORT_H = 512;
    static constexpr int32_t EXPORT_W = 512;
};
